const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('parashakthi', {
  start: (options) => ipcRenderer.invoke('pipeline:start', options), stop: () => ipcRenderer.invoke('pipeline:stop'), cancelAnswer: () => ipcRenderer.invoke('pipeline:cancel-answer'), status: () => ipcRenderer.invoke('pipeline:status'), metrics: () => ipcRenderer.invoke('pipeline:metrics'),
  settings: { get: () => ipcRenderer.invoke('settings:get'), update: (patch) => ipcRenderer.invoke('settings:update', patch), reset: () => ipcRenderer.invoke('settings:reset') },
  profile: { get: () => ipcRenderer.invoke('profile:get'), update: (patch) => ipcRenderer.invoke('profile:update', patch), reset: () => ipcRenderer.invoke('profile:reset') },
  session: { current: () => ipcRenderer.invoke('session:current'), export: () => ipcRenderer.invoke('session:export') },
  sendAudio: (arrayBuffer) => ipcRenderer.invoke('pipeline:audio-chunk', arrayBuffer), sendScreen: (base64Jpeg) => ipcRenderer.invoke('pipeline:screen', base64Jpeg), captureScreenNow: () => ipcRenderer.invoke('pipeline:capture-screen'),
  onCaptureScreen: (handler) => ipcRenderer.on('capture-screen', () => handler()), onHotkeyState: (handler) => ipcRenderer.on('pipeline-hotkey-state', (_e, data) => handler(data)), onPartialTranscript: (handler) => ipcRenderer.on('partial-transcript', (_e, data) => handler(data)), onTranscript: (handler) => ipcRenderer.on('transcript', (_e, data) => handler(data)),
  onAnswerStart: (handler) => ipcRenderer.on('answer-start', (_e, data) => handler(data)), onAnswerToken: (handler) => ipcRenderer.on('answer-token', (_e, token) => handler(token)), onAnswerComplete: (handler) => ipcRenderer.on('answer-complete', (_e, data) => handler(data)), onAnswerCancelled: (handler) => ipcRenderer.on('answer-cancelled', (_e, data) => handler(data)), onTelemetry: (handler) => ipcRenderer.on('telemetry', (_e, data) => handler(data)), onSettingsUpdated: (handler) => ipcRenderer.on('settings-updated', (_e, data) => handler(data)), onProfileUpdated: (handler) => ipcRenderer.on('profile-updated', (_e, data) => handler(data)),
  onAudioStatus: (handler) => ipcRenderer.on('audio-status', (_e, data) => handler(data)), onAsrStatus: (handler) => ipcRenderer.on('asr-status', (_e, data) => handler(data)), onError: (handler) => ipcRenderer.on('pipeline-error', (_e, data) => handler(data))
});
